apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-react-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: buildah-react
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-8-jiri-petnik-buildash-react
    - name: image-repo
      value: quay.io/jpetnik/buildash-react
  pipelineRef:
    name: buildah-react
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
